import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#4CAF50',
  secondary: '#66BB6A',
  accent: '#81C784',
  danger: '#EF5350',
  bg: '#F5F7FA',
  bgGradientStart: '#FFFFFF',
  bgGradientEnd: '#F0F4F8',
  card: '#FFFFFF',
  cardShadow: 'rgba(0,0,0,0.08)',
  border: '#E1E8ED',
  text: '#2C3E50',
  textMuted: '#7F8C8D',
  textLight: '#95A5A6',
  infoBg: '#E8F5E9',
  infoBorder: '#A5D6A7',
  warningBg: '#FFEBEE',
  warningBorder: '#EF9A9A',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  containerCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bg,
  },
  content: {
    padding: 20,
  },
  form: {
    padding: 20,
    gap: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textMuted,
    marginBottom: 16,
    lineHeight: 24,
  },
  input: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    color: colors.text,
    fontSize: 16,
  },
  label: {
    marginTop: 8,
    marginBottom: 8,
    fontWeight: '600',
    color: colors.text,
    fontSize: 14,
    letterSpacing: 0.3,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
    minHeight: 52,
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colors.primary,
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  buttonTextOutline: {
    color: colors.primary,
  },
  card: {
    flex: 1,
    borderRadius: 16,
    padding: 20,
    margin: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    shadowColor: colors.cardShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  glassCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    shadowColor: colors.cardShadow,
    shadowOpacity: 0.25,
    shadowRadius: 20,
  },
  cardDanger: {
    borderColor: colors.danger,
    backgroundColor: colors.warningBg,
    borderWidth: 1.5,
  },
  cardTitle: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '600',
  },
  cardValue: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
  },
  cardValueDanger: {
    color: colors.danger,
  },
  cardSubtitle: {
    fontSize: 13,
    color: colors.textLight,
    marginTop: 6,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  warningBox: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warningBorder,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 18,
    marginVertical: 12,
  },
  warningText: {
    color: colors.danger,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginTop: 24,
    marginBottom: 12,
    color: colors.text,
  },
  mealItem: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.cardShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 4,
    elevation: 1,
  },
  mealTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  mealMeta: {
    color: colors.textMuted,
    marginTop: 4,
    fontSize: 14,
  },
  mealTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 8,
  },
  mealTypeButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  mealTypeButtonActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  mealTypeText: {
    color: colors.accent,
    fontWeight: '600',
  },
  mealTypeTextActive: {
    color: '#04130c',
  },
  infoBox: {
    backgroundColor: colors.infoBg,
    borderColor: colors.infoBorder,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 16,
    marginVertical: 10,
  },
  infoText: {
    color: colors.text,
    marginBottom: 4,
    fontSize: 14,
    lineHeight: 20,
  },
  error: {
    color: colors.danger,
    marginTop: -4,
    marginBottom: 4,
    fontSize: 13,
  },
  muted: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  suggestionCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    borderColor: colors.border,
    borderWidth: 1,
    shadowColor: colors.cardShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  badge: {
    marginTop: 8,
    color: colors.primary,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontSize: 12,
  },
  heroContainer: {
    padding: 28,
    borderRadius: 20,
    marginBottom: 24,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.cardShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  heroSubtitle: {
    color: colors.textMuted,
    fontSize: 16,
    lineHeight: 24,
    lineHeight: 22,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginVertical: 18,
  },
  neonPill: {
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: colors.infoBg,
    borderColor: colors.infoBorder,
    borderWidth: 1,
    color: colors.primary,
    alignSelf: 'flex-start',
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
});
